[permissions]
# Global allowed users/teams (fallback/default access)
users = ["Pacificdubey"]
teams = ["probot-admin"]

[environment_targets.dev]
branches = ["feature/*", "bugfix/*"]
users = ["Pacificdubey", "Pardomain"]
teams = ["probot-admin","probot-developer"]

[environment_targets.stage]
branches = ["release/*"]
users = ["Pacificdubey"]
teams = ["probot-admin"]

[environment_targets.production]
branches = ["main"]
users = ["Pacificdubey"]
teams = ["probot-admin"]

production_environments = ["production", "prod"]

stable_branch = "main"

skip_ci = false

checks = [
  "int",
  "scan"
]

ignored_checks = [
  "scan"
]
