[environment_targets.dev]
branches = ["feature/*", "bugfix/*"]
users = ["Pacificdubey", "Pardomain"]
teams = ["probot-admin","probot-developer"]

[environment_targets.stage]
branches = ["release/*"]
users = ["Pacificdubey"]
teams = ["probot-admin"]

[checks]
skip_ci = false
required = ["lint", "scan"]
ignored = ["scan"]
