name: CI Scan

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "✅ Lint successful"
          exit 1
            

  scan:
    runs-on: ubuntu-latest
    steps:
      - run: echo "✅ Scan successful"
