name: Deploy Workflow
 
on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: "Pull Request Number"
        required: true
        type: string
      comment_author:
        description: "Author of the deploy comment"
        required: true
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Display Inputs
        run: |
          echo "Triggered by PR #${{ github.event.inputs.pr_number }}"
          echo "Comment Author: ${{ github.event.inputs.comment_author }}"
      - name: Deploy Application
        run: |
          echo "Deploying application for PR #${{ github.event.inputs.pr_number }}..."
 
